# /k8s/worker-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatterbox-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatterbox-worker
  template:
    metadata:
      labels:
        app: chatterbox-worker
    spec:
      containers:
        - name: chatterbox-worker
          image: harshrange/chatterbox-worker:latest
          imagePullPolicy: Always
          env:
            - name: REDIS_HOST
              value: redis-service
            - name: REDIS_PORT
              value: "6379"
